# Generated by Django 4.1.2 on 2022-10-30 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostName', models.CharField(max_length=100)),
                ('OSName', models.CharField(max_length=100)),
                ('OSVersion', models.CharField(max_length=100)),
                ('OSManf', models.CharField(max_length=100)),
                ('OSConf', models.CharField(max_length=100)),
                ('Owner', models.CharField(max_length=100)),
                ('BootTime', models.DateTimeField()),
                ('Manf', models.CharField(max_length=100)),
                ('Model', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('BIOSVers', models.CharField(max_length=100)),
                ('TimeZone', models.CharField(max_length=100)),
                ('TotPhysMem', models.IntegerField()),
                ('AvailPhysMem', models.IntegerField()),
                ('Domain', models.CharField(max_length=100)),
                ('LogonServer', models.CharField(max_length=100)),
                ('TransDate', models.DateTimeField()),
                ('Serial', models.CharField(max_length=100)),
                ('Hotfixes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manf', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Expiry', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manf', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('Device', models.DateTimeField()),
                ('Price', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
