# Generated by Django 4.0.8 on 2022-11-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('manf', models.TextField(blank=True, db_column='Manf', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('expiry', models.DateField(blank=True, db_column='Expiry', null=True)),
            ],
            options={
                'db_table': 'contracts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('hostname', models.TextField(blank=True, db_column='HostName', primary_key=True, serialize=False)),
                ('osname', models.TextField(blank=True, db_column='OSName', null=True)),
                ('osversion', models.TextField(blank=True, db_column='OSVersion', null=True)),
                ('osmanf', models.TextField(blank=True, db_column='OSManf', null=True)),
                ('osconf', models.TextField(blank=True, db_column='OSConf', null=True)),
                ('owner1', models.TextField(blank=True, db_column='Owner1', null=True)),
                ('boottime', models.DateField(blank=True, db_column='BootTime', null=True)),
                ('manf', models.TextField(blank=True, db_column='Manf', null=True)),
                ('model', models.TextField(blank=True, db_column='Model', null=True)),
                ('type1', models.TextField(blank=True, db_column='Type1', null=True)),
                ('biosvers', models.TextField(blank=True, db_column='BIOSVers', null=True)),
                ('timezone', models.TextField(blank=True, db_column='TimeZone', null=True)),
                ('totphysmem', models.TextField(blank=True, db_column='TotPhysMem', null=True)),
                ('availphysmem', models.TextField(blank=True, db_column='AvailPhysMem', null=True)),
                ('domain', models.TextField(blank=True, db_column='Domain', null=True)),
                ('logonserver', models.TextField(blank=True, db_column='LogonServer', null=True)),
                ('transdate', models.DateField(blank=True, db_column='TransDate', null=True)),
                ('serial1', models.TextField(blank=True, db_column='Serial1', null=True)),
                ('processors', models.TextField(blank=True, db_column='Processors', null=True)),
                ('hotfixes', models.TextField(blank=True, db_column='Hotfixes', null=True)),
            ],
            options={
                'db_table': 'hardware',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('manf', models.TextField(blank=True, db_column='Manf', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('user1', models.TextField(blank=True, db_column='User1', null=True)),
                ('device', models.TextField(blank=True, db_column='Device', null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'software',
                'managed': False,
            },
        ),
    ]
