# Generated by Django 4.0.8 on 2022-11-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hardware',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'managed': True},
        ),
    ]
