# Generated by Django 4.0.8 on 2022-11-14 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_contract_options_alter_hardware_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hardware',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'managed': False},
        ),
    ]
